# Generated by Django 6.0.4 on 2026-04-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescriptions',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
