# Generated by Django 6.0.4 on 2026-04-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_dashboard', '0002_jobdescriptions_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescriptions',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
