# Generated by Django 6.0.4 on 2026-04-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_dashboard', '0003_jobdescriptions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescriptions',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
