# Generated by Django 6.0.4 on 2026-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='isHr',
            field=models.BooleanField(default=False),
        ),
    ]
