# Generated by Django 6.0.4 on 2026-05-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='feedback',
        ),
        migrations.AddField(
            model_name='resume',
            name='is_resume',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='match_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='project_categories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills_extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills_matched',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills_missing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='suggestions_high',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='suggestions_low',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='suggestions_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='total_expreience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
