# Generated by Django 6.0.4 on 2026-05-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_dashboard', '0002_remove_resume_extracted_text_remove_resume_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='project_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills_extra',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills_matched',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills_missing',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
