# Generated by Django 6.0.4 on 2026-05-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_dashboard', '0003_alter_resume_project_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='total_expreience',
            new_name='total_experience',
        ),
    ]
