# Generated by Django 6.0.4 on 2026-05-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_dashboard', '0004_rename_total_expreience_resume_total_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='suggestions_high',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='suggestions_low',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='suggestions_medium',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
